name: Build and push to aws
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Build project
        run: dotnet restore && dotnet publish -o site

      - name: Create ZIP package
        run: cd site; zip ../site.zip *;

      - name: Deploy to aws EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
           aws_access_key: ${{secrets.AWS__ACCESS_KEY_ID}}
           aws_secret_key: ${{secrets.AWS__SECRET_ACCESS_KEY}}
           application_name: MyApplication
           environment_name: MyApplication-env
           version_label: ${{ github.run_id }}
           region: eu-north-1
           deployment_package: site.zip


